# Generated by Django 3.2.6 on 2021-12-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20211130_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_date',
            field=models.CharField(default='2021-12-01', max_length=100),
        ),
    ]
